#include <vector>
#include "realms.h"

std::vector<Species> sapientSpecies = {
    {   -1, "human",        "Hu",   Stance::Biped,  Wings::None,    175 },
    {   -1, "gryphon",      "Gr",   Stance::Quad,   Wings::Back,    85  },
    {   -1, "dragon",       "Dr",   Stance::Quad,   Wings::Back,    0 },
    {   -1, "wyvern",       "Wy",   Stance::Quad,   Wings::Arm,     179 },
    {   -1, "demon",        "De",   Stance::Biped,  Wings::None,    71 },
    {   -1, "hellhound",    "Hh",   Stance::Quad,   Wings::None,    0 },
    {   -1, "gargoyle",     "Ga",   Stance::Biped,  Wings::Back,    0 },
    {   -1, "satyr",        "Sa",   Stance::Biped,  Wings::None,    102 },
    {   -1, "harpy",        "Ha",   Stance::Biped,  Wings::Arm,     0 },
    {   -1, "lizardfolk",   "Lz",   Stance::Biped,  Wings::None,    0 },
    {   -1, "ratling",      "Rt",   Stance::Biped,  Wings::None,    0 },
    {   -1, "centaur",      "Cn",   Stance::Taur,   Wings::None,    0 },
    {   -1, "nemean lion",  "Nl",   Stance::Biped,  Wings::None,    192 },
    {   -1, "werewolf",     "Ww",   Stance::Biped,  Wings::None,    194 },
    {   -1, "DC",           "Dc",   Stance::Thero,  Wings::None,    0 },
    {   -1, "batfolk",      "Bf",   Stance::Biped,  Wings::Arm,     0 },
    {   -1, "minotaur",     "Mt",   Stance::Biped,  Wings::None,    0 },
    {   -1, "imp",          "Im",   Stance::Biped,  Wings::Back,    104 },
    {   -1, "sasquatch",    "Sq",   Stance::Biped,  Wings::None,    0 },
    {   -1, "raptor",       "Rp",   Stance::Thero,  Wings::None,    0 },
    {   -1, "foxtaur",      "Ft",   Stance::Taur,   Wings::None,    0 },
    {   -1, "gnoll",        "Gn",   Stance::Biped,  Wings::None,    132 },
    {   -1, "hexbeast",     "Hb",   Stance::Biped,  Wings::None,    0 },
    {   -1, "kobold",       "Kb",   Stance::Biped,  Wings::None,    59 },
    {   -1, "troll",        "Tr",   Stance::Biped,  Wings::None,    147 },
    {   -1, "warg",         "Wa",   Stance::Quad,   Wings::None,    0 },
    {   -1, "cervine-taur", "Ct",   Stance::Taur,   Wings::None,    0 },
    {   -1, "liontaur",     "Lt",   Stance::Taur,   Wings::None,    0 },
    {   -1, "garg. beast",  "Gb",   Stance::Quad,   Wings::None,    0 },
    {   -1, "draconian",    "Dn",   Stance::Biped,  Wings::Back,    0 },
};
