#include <vector>
#include "realms.h"

std::vector<const char*> realmNames = {
    "Council's Duchy of the Confidences",
    "Country of the Small Winds",
    "Ebony Fingers Barony",
    "Fifty Sables Barony",
    "Giant Fortuitous Province",
    "Hare's Land",
    "Infernal Serpent's Fief",
    "Infernal Superior Ogres Realm",
    "Kingdom of the Carnage",
    "Long Sigils Country",
    "New Platinum Angel's Country",
    "One Hundred Codexes Country",
    "Prince's Realm of the Market",
    "Royal Country",
    "Tiny Barony",
    "Baron's Realm of the Spirits",
    "Barony of the Long Placid Banes",
    "Big Ox's Land",
    "Charioteer's Duchy of the Eagles",
    "County of the Flail",
    "Duchy of the Rocky Providences",
    "Earldom of the Infernal Emperesses",
    "Earldom of the Lawful Ethereal Seahorse's Lava",
    "Holy Berry Fief",
    "Kingdom of the Phoenix",
    "New Winter Lives Fief",
    "Realm of the Nine Pleasant Bones",
    "Roaring Marchessies of the Soul",
    "Slayer's Realm",
    "Teacher's Realm",
    "Copper Empire of the Traveller",
    "Country of the One Hundred Infernal Palms",
    "Earldom of the Providence",
    "Earldom of the Water",
    "Empire of the South Dragon's Skull",
    "Fire Earldom",
    "Giant Kingdom of the Illusions",
    "Long Buffalo's Fief",
    "Monk's Country of the Rats",
    "Realm of the Spells",
    "State of the Gauntlets",
    "Turtle's Realm of the Slayer",
    "Unholy Tigers Country",
    "Unnamed Fief",
    "Wizard's County",
    "Chaotic Wise Animal's Kingdom",
	"Country of the Blade",
	"Duchy of the Chagrin",
	"Duchy of the Flea",
	"Fief of the Shrew",
	"Kingdom of the First Deer",
	"Long Land",
	"Lost Lanterns Marchessies",
	"Mammoth Placid State",
	"Marchessies of the Four Unholy Ghosts",
	"Marchessies of the Golden Flames",
	"Marchessies of the Mighty Crystal Charioteer",
	"Marchessies of the Ruddy Locusts",
	"Raven's Empire of the Bows",
	"Sugar Fishers Kingdom",
	"Blessed Diamond Knight's Earldom",
	"Broad Woman's Earldom",
	"Earldom of the Mighty Summoner",
	"Empire of the Grimoires",
	"Fief of the Branches",
	"Kingdom of the Nine Conceptions",
	"Kingdom of the One Thousand Lawful Men",
	"Kite's Duchy",
	"Knight's Fief",
	"Land of the Small Fair Fox",
	"Large Country",
	"Lava Realm",
	"Mighty Count's Duchy",
	"Stone Fools Earldom",
	"Unnamed Wealthy Noose Fief",
	"Barony of the Nine Palaces",
	"Barony of the Penguin's Mead",
	"Berserker Land",
	"Earldom of the Long Low Knight",
	"Fief of the State Palm",
	"Flathead Land",
	"Four Sands Barony",
	"Marchessies of the Grand Rough Pipes",
	"Midway Wolf's Country",
	"Monk's State of the Hero",
	"New Strong Earldom",
	"Province of the Unnamed Bane's Cat",
	"Realm of the Grand Gold Phoenix's Volcano",
	"Realm of the Unholy Red Arrow",
	"Wood Marchessies of the Love",
};

std::vector<Species> sapientSpecies = {
    {   1,  "human",        Stance::Biped, Wings::None, false, 175 },
    {   2,  "gryphon",      Stance::Quad,  Wings::Back, false, 85  },
    {   3,  "dragon",       Stance::Quad,  Wings::Back, false, 0 },
    {   4,  "wyvern",       Stance::Quad,  Wings::Arm,  false, 0 },
    {   5,  "demon",        Stance::Biped, Wings::None, false, 0 },
    {   6,  "hellhound",    Stance::Quad,  Wings::None, false, 0 },
    {   7,  "gargoyle",     Stance::Biped, Wings::Back, false, 0 },
    {   8,  "satyr",        Stance::Biped, Wings::None, false, 0 },
    {   9,  "harpy",        Stance::Biped, Wings::Arm,  false, 0 },
    {   10, "lizardfolk",   Stance::Biped, Wings::None, true,  0 },
    {   11, "ratling",      Stance::Biped, Wings::None, true,  0 },
    {   12, "centaur",      Stance::Taur,  Wings::None, false, 0 },
    {   13, "sphinx",       Stance::Quad,  Wings::None, false, 0 },
    {   14, "werewolf",     Stance::Biped, Wings::None, true,  0 },
    {   15, "DC",           Stance::Thero, Wings::None, false, 0 },
    {   16, "batfolk",      Stance::Biped, Wings::Arm,  true,  0 },
    {   17, "minotaur",     Stance::Biped, Wings::None, true,  0 },
    {   18, "imp",          Stance::Biped, Wings::Back, false, 0 },
    {   19, "sasquatch",    Stance::Biped, Wings::None, false, 0 },
    {   20, "raptor",       Stance::Thero, Wings::None, false, 0 },
    {   21, "foxtaur",      Stance::Taur,  Wings::None, true,  0 },
    {   22, "gnoll",        Stance::Biped, Wings::None, true,  0 },
    {   23, "hexbeast",     Stance::Biped, Wings::None, false, 0 },
    {   24, "kobold",       Stance::Biped, Wings::None, false, 0 },
    {   25, "troll",        Stance::Biped, Wings::None, false, 0 },
    {   26, "cubi",         Stance::Biped, Wings::Back, false, 0 },
    {   27, "warg",         Stance::Quad,  Wings::None, false, 0 },
    {   28, "e.dragon",     Stance::Quad,  Wings::None, false, 0 },
    {   28, "liontaur",     Stance::Taur,  Wings::None, false, 0 },
};

